[package]
name = "pit"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "PitFast local execution CLI"

[dependencies]
anyhow.workspace = true
clap.workspace = true
pit-node = { path = "../pit-node" }
pit-scheduler = { path = "../../crates/pit-scheduler" }
tracing-subscriber.workspace = true
